POST http://localhost:3000/api/clients
Content-Type: application/json
{
    "name": "Rigoberto",
    "surname":"El cojo",
}

###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name": "Nil",
    "surname":"Abella",
    "rango":"oficial",
    "password": "password",
    "username": "NilAL",
    "category":"herrero"
    
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "NilAL",
    "password": "password"
}

###
DELETE http://localhost:3000/api/users/

###

GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/clients


###
POST http://localhost:3000/api/orders
Content-Type: application/json

{
   "task":"fabricar",
   "product_type":"espada",
   "product_subtype":"mandoble",
   "order_status":"active",
   "start_date":"2023/08/21",
   "end_date":"",
   "price":"234",
   "obs":"Estamos creando la empuñadura desde cero",
   "sub_task1":"pulir",
   "sub_task2":"afilar",
   "sub_task3":"",
   "sub_task1_status":"proceso",
   "sub_task2_status":"termianda",
   "sub_task3_status":""
  }


###
GET http://localhost:3000/api/orders

