POST http://localhost:3000/api/clients
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2ODUyNjcwMDQsImlhdCI6MTY3NzQ5NDYwNH0.9ewSj-i4qXuJ_OBy0a3AHKE8-2B7XSE7Na8qO5DpFhc

{
    "name": "Rigoberto",
    "surname":"El cojo",
    "address":"El puente roto a la derecha",
    "birthdate":"1983-01-15",
    "email":"rigobertocojo@gmail.com",
    "age":"40"
}
###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "Miquel",
    "surname":"Abella",
    "rango":"maestre",
    "guild":"herrero",
    "email": "mag@gmail.com",
    "password": "password"    
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "mag@gmail.com",
    "password": "password"
}

###
DELETE http://localhost:3000/api/users/5

###

GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/clients
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2ODUyNjcwMDQsImlhdCI6MTY3NzQ5NDYwNH0.9ewSj-i4qXuJ_OBy0a3AHKE8-2B7XSE7Na8qO5DpFhc